
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Samudra~
 */
public class Frame1 extends javax.swing.JFrame {
    String tmp ="";
    double ti, bt, h1;
    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfBerat = new javax.swing.JTextField();
        tfDiagnosa2 = new javax.swing.JTextField();
        tfTinggi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbLakilaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        bKeluar = new javax.swing.JButton();
        bHitung = new javax.swing.JButton();
        bCobalagi = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tfIdeal = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfDiagnosa1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Hasil Diagnosa Kesehatan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("CEK IDEAL TUBUH");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nama");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("kg");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Berat Badan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        tfBerat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfBeratActionPerformed(evt);
            }
        });
        getContentPane().add(tfBerat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 40, -1));

        tfDiagnosa2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDiagnosa2ActionPerformed(evt);
            }
        });
        getContentPane().add(tfDiagnosa2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 360, -1));

        tfTinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTinggiActionPerformed(evt);
            }
        });
        getContentPane().add(tfTinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 40, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Tinggi");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("cm");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        rbLakilaki.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbLakilaki.setText("Laki - laki");
        getContentPane().add(rbLakilaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        rbPerempuan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rbPerempuan.setText("Perempuan");
        getContentPane().add(rbPerempuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        bKeluar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bKeluar.setText("Keluar");
        bKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 100, -1));

        bHitung.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bHitung.setText("Hitung");
        bHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungActionPerformed(evt);
            }
        });
        getContentPane().add(bHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 100, -1));

        bCobalagi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bCobalagi.setText("Coba Lagi");
        bCobalagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCobalagiActionPerformed(evt);
            }
        });
        getContentPane().add(bCobalagi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 100, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Jenis Kelamin");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, -1));

        tfIdeal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIdealActionPerformed(evt);
            }
        });
        getContentPane().add(tfIdeal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 40, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("kg");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Berat badan ideal anda adalah");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        tfNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamaActionPerformed(evt);
            }
        });
        getContentPane().add(tfNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 140, -1));

        tfDiagnosa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDiagnosa1ActionPerformed(evt);
            }
        });
        getContentPane().add(tfDiagnosa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 360, -1));

        setBounds(0, 0, 451, 414);
    }// </editor-fold>//GEN-END:initComponents

    private void tfBeratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfBeratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfBeratActionPerformed

    private void tfDiagnosa2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDiagnosa2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDiagnosa2ActionPerformed

    private void tfTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTinggiActionPerformed

    private void bKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKeluarActionPerformed
        dispose();
    }//GEN-LAST:event_bKeluarActionPerformed

    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
        if (tfBerat.getText().equals("")||tfTinggi.getText().equals("")||tfNama.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Kotak isian belum diisi");
        }
        else if (rbPerempuan.isSelected()||rbLakilaki.isSelected())
        {
            try
            {
                Proses();
            } catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, "Inputan ada yang salah");
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Jenis kelamin Belum diisi");
        }
    }//GEN-LAST:event_bHitungActionPerformed

    private void bCobalagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCobalagiActionPerformed
        tfNama.setText("");
        tfTinggi.setText("");
        tfBerat.setText("");
        buttonGroup1.clearSelection();
        tfIdeal.setText("");
        tfDiagnosa1.setText("");
        tfDiagnosa2.setText("");
    }//GEN-LAST:event_bCobalagiActionPerformed

    private void tfIdealActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIdealActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfIdealActionPerformed

    private void tfNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNamaActionPerformed

    private void tfDiagnosa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDiagnosa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDiagnosa1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCobalagi;
    private javax.swing.JButton bHitung;
    private javax.swing.JButton bKeluar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbLakilaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextField tfBerat;
    private javax.swing.JTextField tfDiagnosa1;
    private javax.swing.JTextField tfDiagnosa2;
    private javax.swing.JTextField tfIdeal;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTinggi;
    // End of variables declaration//GEN-END:variables

    private void Proses() {
        ti = Double.valueOf(tfTinggi.getText());
        bt = Double.valueOf(tfBerat.getText());
        
        if (rbPerempuan.isSelected()) 
        {
            h1 = (ti - 100 )* 1;
        }
        else if (rbLakilaki.isSelected()) 
        {
            h1 = (ti - 104 )* 1;
        }
        tmp = h1+"";
        if (h1<bt) 
        {
            tfIdeal.setText(tmp);
            tfDiagnosa1.setText("Maaf "+tfNama.getText()+", Sepertinya Anda overwight");
            tfDiagnosa2.setText("Perbanyaklah Berolahraga dan hindari makanan berkolesterol");
        }
        else if (h1>bt) {
            tfIdeal.setText(tmp);
            tfDiagnosa1.setText("Maaf "+tfNama.getText()+", Sepertinya Anda underwight");
            tfDiagnosa2.setText("Perbanyaklah mengkonsumsi makanan berkarbohidrat");
        }
        else
        {
            tfIdeal.setText(tmp);
            tfDiagnosa1.setText("Halo "+tfNama.getText()+", berat badan Anda sudah ideal");
            tfDiagnosa2.setText("Lanjutkan pola makan teratur dan pola hidup sehat");
        }
    }
}
